# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='starr_date',
            new_name='start_date',
        ),
    ]
